freebsd_13_task:
  timeout_in: 120m
  freebsd_instance:
    image: freebsd-13-0-release-amd64
  # GCP image defaults to TCP/UDP blackhole - see gh-91824
  network_setup_script:
    - sysctl net.inet.tcp.blackhole=0
    - sysctl net.inet.udp.blackhole=0
    - sysctl net.inet.tcp.keepinit=15000
  install_script:
    pkg install -y pkg
  build_script:
    - mkdir build
    - cd build
    - ../configure
    - make -j$(sysctl -n hw.ncpu)
  debug_urllib2net_script:
    sh debug_script.sh test_urllib2net
  debug_asyncio_script:
    sh debug_script.sh test_asyncio
  debug_dtrace_script:
    sh debug_script.sh test_dtrace
  test_script:
    - cd build
    - make test
