freebsd_task:
  freebsd_instance:
    matrix:
    - image: freebsd-12-3-release-amd64
    - image: freebsd-13-0-release-amd64
  build_script:
    - mkdir build
    - cd build
    - ../configure
    - make -j$(sysctl -n hw.ncpu)
  test_script:
    - rm Lib/test/test_dtrace.py
    - cd build
    # dtrace fails to build on FreeBSD - see gh-73263
    - make test TESTOPTS="-u-network"
