freebsd_task:
  freebsd_instance:
    matrix:
    - image: freebsd-13-2-release-amd64
  sysctl_script:
    - sysctl net.inet.tcp.blackhole=0
    - sysctl net.inet.udp.blackhole=0
  build_script:
    - mkdir build
    - cd build
    - ../configure
    - make -j$(sysctl -n hw.ncpu)
  test_script:
    - cd build
    # dtrace fails to build on FreeBSD - see gh-73263
    - make buildbottest TESTOPTS="-j2 -x test_dtrace"
